Start using invoke for Python-based tasks
alphagov/digitalmarketplace-aws pull request #982
Opened 2021-08-18 11:32 UTC by bjgill

So that we can manage this repo in the same way we do all our others.

See https://github.com/alphagov/digitalmarketplace-scripts/pull/649 for an example of how we've done this for other repos. There's a lot of non-Python stuff in the Makefile, so I've left that as-is for the moment in the interests of time.

As part of this, I needed to switch us over to using pip-compile. This has no immediate effect, but might make future dependency management easier.

2021-08-18 18:47 UTC, phantas requested changes
couple of changes to github flows, otherwise looks ok 👍

2021-08-18 18:47 UTC, phantas commented on .github/workflows/test.yml
>          run: make requirements-dev
```suggestion
        run: invoke requirements-dev
```
likewise for line 31 (I can't add as a suggestion...) which should be replaced for
```
        run: invoke test
```

2021-08-19 10:12 UTC, bjgill commented
Don't know why that's not working - it's doing the same thing as our other repos. I'll investigate...

2021-08-19 11:31 UTC, bjgill commented
OK. That fixes the problem. Once merged, I'll deploy an app to make sure I haven't broken anything.

2021-08-19 12:16 UTC, phantas approved these changes
LGTM! 🚀

2021-08-19 12:53 UTC, merged